[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo", "php82Extensions.pdo_sqlite", "php82Extensions.mbstring", "php82Extensions.openssl", "php82Extensions.tokenizer", "php82Extensions.xml", "php82Extensions.ctype", "php82Extensions.fileinfo", "php82Extensions.curl", "nginx"]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache"
]

[phases.build]
cmds = ["echo 'Build phase complete'"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=${PORT:-8000}"
